name: "Mirror Hub Action."
description: "Mirror the organization repos between hub (github/gitee)."
author: "yikun"
branding:
  icon: "upload-cloud"
  color: "gray-dark"
inputs:
  dst_key:
    description: "The private SSH key which is used to to push code in destination hub."
    required: true
  dst:
    description: "Destination name. Such as `gitee/kunpengcompute`."
    required: true
  src:
    description: "Source name. Such as `github/kunpengcompute`."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dst_key }}
    - ${{ inputs.src }}
    - ${{ inputs.dst }}
